export type CategorySlug =
  | "buttons"
  | "surfaces"
  | "type"
  | "chips"
  | "controls"
  | "chrome";

export type World = "ink" | "paper" | "mist" | "grid" | "studio" | "night";

export type Specimen = {
  id: number;
  slug: string;
  name: string;
  nameRu: string;
  category: CategorySlug;
  world: World;
  tags: string[];
  note: string;
  css: string;
};

export type Category = {
  slug: CategorySlug;
  label: string;
  labelEn: string;
  range: [number, number];
  blurb: string;
};

export const CATEGORIES: Category[] = [
  {
    slug: "buttons",
    label: "Кнопки",
    labelEn: "Buttons",
    range: [1, 24],
    blurb: "Вес, радиус, характер нажатия — от штампа до госта.",
  },
  {
    slug: "surfaces",
    label: "Боксы",
    labelEn: "Surfaces",
    range: [25, 46],
    blurb: "Карточки, панели, бумага, окна и рамки.",
  },
  {
    slug: "type",
    label: "Тайтлы",
    labelEn: "Titles",
    range: [47, 62],
    blurb: "Иерархия заголовков: кикер, глава, выноска, капитель.",
  },
  {
    slug: "chips",
    label: "Вложения",
    labelEn: "Attachments",
    range: [63, 80],
    blurb: "Файлы, теги, бейджи, превью ссылок и статусы.",
  },
  {
    slug: "controls",
    label: "Контролы",
    labelEn: "Controls",
    range: [81, 92],
    blurb: "Поля, тогглы, сегменты, слайдеры, степпер.",
  },
  {
    slug: "chrome",
    label: "Хром",
    labelEn: "Chrome",
    range: [93, 100],
    blurb: "Баннеры, тосты, табы, крошки, пустые состояния.",
  },
];

export const SPECIMENS: Specimen[] = [
  {
    id: 1,
    slug: "ink-fill",
    name: "Ink Fill",
    nameRu: "Чернила",
    category: "buttons",
    world: "ink",
    tags: ["fill", "product"],
    note: "Плотная заливка бумажным тоном. Один акцент на тёмном поле.",
    css: `.btn { background: #f2efe9; color: #0c0c0b; border-radius: 8px; padding: 12px 20px; font-weight: 500; }
.btn:active { scale: 0.96; }`,
  },
  {
    id: 2,
    slug: "hairline-ghost",
    name: "Hairline Ghost",
    nameRu: "Контур",
    category: "buttons",
    world: "ink",
    tags: ["ghost", "quiet"],
    note: "Волосная линия вместо заливки. Для вторичных действий.",
    css: `.btn { background: transparent; color: #f2efe9; box-shadow: inset 0 0 0 1px rgba(242,239,233,.18); border-radius: 8px; }`,
  },
  {
    id: 3,
    slug: "brutal-stamp",
    name: "Brutal Stamp",
    nameRu: "Штамп",
    category: "buttons",
    world: "paper",
    tags: ["brutal", "caps"],
    note: "Нулевой радиус, жирная обводка, капс. Как печать на бланке.",
    css: `.btn { background: #0c0c0b; color: #f2efe9; border: 3px solid #0c0c0b; letter-spacing: .18em; text-transform: uppercase; font-size: 11px; }`,
  },
  {
    id: 4,
    slug: "soft-pill",
    name: "Soft Pill",
    nameRu: "Капсула",
    category: "buttons",
    world: "mist",
    tags: ["pill", "soft"],
    note: "Полный радиус и приглушённая заливка. Продуктовый жест.",
    css: `.btn { background: #1a1916; color: #f2efe9; border-radius: 999px; padding: 12px 22px; }`,
  },
  {
    id: 5,
    slug: "terminal-ok",
    name: "Terminal OK",
    nameRu: "Терминал",
    category: "buttons",
    world: "night",
    tags: ["mono", "technical"],
    note: "Моноширинный подтверждение в квадратных скобках.",
    css: `.btn { font-family: ui-monospace, monospace; color: #b7e4c7; background: #0b120e; box-shadow: inset 0 0 0 1px #1d3a28; }`,
  },
  {
    id: 6,
    slug: "swiss-caps",
    name: "Swiss Caps",
    nameRu: "Швейцарский",
    category: "buttons",
    world: "paper",
    tags: ["swiss", "editorial"],
    note: "Мелкие капители, трекинг, линия появляется снизу.",
    css: `.btn { background: none; letter-spacing: .22em; text-transform: uppercase; font-size: 11px; }
.btn:hover { box-shadow: 0 1px 0 currentColor; }`,
  },
  {
    id: 7,
    slug: "split-dual",
    name: "Split Dual",
    nameRu: "Сплит",
    category: "buttons",
    world: "ink",
    tags: ["split", "product"],
    note: "Две зоны в одном контроле: действие и меню.",
    css: `.split { display: flex; overflow: hidden; border-radius: 8px; }
.split > * { background: #f2efe9; color: #0c0c0b; }
.split .menu { box-shadow: inset 1px 0 0 #0c0c0b22; }`,
  },
  {
    id: 8,
    slug: "icon-disc",
    name: "Icon Disc",
    nameRu: "Диск",
    category: "buttons",
    world: "studio",
    tags: ["icon", "round"],
    note: "Круглая иконка без подписи. Только жест.",
    css: `.btn { width: 44px; height: 44px; border-radius: 50%; background: #0c0c0b; color: #f2efe9; }`,
  },
  {
    id: 9,
    slug: "underscore",
    name: "Underscore",
    nameRu: "Подчёркивание",
    category: "buttons",
    world: "paper",
    tags: ["text", "editorial"],
    note: "Текстовая кнопка с анимированной линией.",
    css: `.btn { background: none; }
.btn span { background: linear-gradient(currentColor, currentColor) 0 100% / 0 1px no-repeat; }
.btn:hover span { background-size: 100% 1px; }`,
  },
  {
    id: 10,
    slug: "emboss",
    name: "Emboss",
    nameRu: "Тиснение",
    category: "buttons",
    world: "mist",
    tags: ["soft", "depth"],
    note: "Свет сверху, тень снизу — слабо выпуклая пластина.",
    css: `.btn { background: #d8d4cb; border-radius: 12px; box-shadow: inset 0 1px 0 #fff8, 0 1px 2px #0002; }`,
  },
  {
    id: 11,
    slug: "offset-ring",
    name: "Offset Ring",
    nameRu: "Двойной контур",
    category: "buttons",
    world: "ink",
    tags: ["outline", "focus"],
    note: "Внутренняя кнопка и внешнее кольцо с зазором.",
    css: `.btn { box-shadow: 0 0 0 1px #f2efe9, 0 0 0 5px #0c0c0b, 0 0 0 6px #f2efe944; }`,
  },
  {
    id: 12,
    slug: "arrow-slide",
    name: "Arrow Slide",
    nameRu: "Стрелка",
    category: "buttons",
    world: "paper",
    tags: ["motion", "icon"],
    note: "Стрелка выезжает на ховер. Направление читается сразу.",
    css: `.btn .arrow { transform: translateX(0); }
.btn:hover .arrow { transform: translateX(4px); }`,
  },
  {
    id: 13,
    slug: "press-block",
    name: "Press Block",
    nameRu: "Пресс",
    category: "buttons",
    world: "studio",
    tags: ["brutal", "depth"],
    note: "Толстая нижняя кромка. Нажатие утапливает блок.",
    css: `.btn { background: #0c0c0b; color: #f2efe9; box-shadow: 0 4px 0 #3a3934; }
.btn:active { transform: translateY(3px); box-shadow: 0 1px 0 #3a3934; }`,
  },
  {
    id: 14,
    slug: "quiet-wash",
    name: "Quiet Wash",
    nameRu: "Смывка",
    category: "buttons",
    world: "ink",
    tags: ["quiet", "product"],
    note: "Почти тот же тон, что и поле. Шепчет, не кричит.",
    css: `.btn { background: #1c1c19; color: #f2efe9; box-shadow: inset 0 0 0 1px #ffffff10; }`,
  },
  {
    id: 15,
    slug: "dash-frame",
    name: "Dash Frame",
    nameRu: "Пунктир",
    category: "buttons",
    world: "paper",
    tags: ["dashed", "add"],
    note: "Пунктир = «добавить». Пустое действие.",
    css: `.btn { border: 1.5px dashed #1a191688; background: transparent; }`,
  },
  {
    id: 16,
    slug: "sharp-square",
    name: "Sharp Square",
    nameRu: "Квадрат",
    category: "buttons",
    world: "grid",
    tags: ["sharp", "technical"],
    note: "Жёсткий прямоугольник без скруглений. Чертёж.",
    css: `.btn { border-radius: 0; background: #f2efe9; color: #0c0c0b; }`,
  },
  {
    id: 17,
    slug: "leading-icon",
    name: "Leading Icon",
    nameRu: "С иконкой",
    category: "buttons",
    world: "ink",
    tags: ["icon", "product"],
    note: "Иконка слева, оптический сдвиг паддинга.",
    css: `.btn { display: inline-flex; gap: 8px; padding: 12px 16px 12px 14px; }`,
  },
  {
    id: 18,
    slug: "naked-text",
    name: "Naked Text",
    nameRu: "Текст",
    category: "buttons",
    world: "paper",
    tags: ["text", "quiet"],
    note: "Никакой хромированной оболочки. Только слово.",
    css: `.btn { background: none; padding: 8px 0; font-weight: 500; }`,
  },
  {
    id: 19,
    slug: "dual-tone",
    name: "Dual Tone",
    nameRu: "Двутон",
    category: "buttons",
    world: "ink",
    tags: ["split", "icon"],
    note: "Тёмная зона иконки + светлая зона текста.",
    css: `.btn { display: flex; overflow: hidden; border-radius: 8px; }
.btn i { background: #0c0c0b; color: #f2efe9; }
.btn b { background: #f2efe9; color: #0c0c0b; }`,
  },
  {
    id: 20,
    slug: "pulse-load",
    name: "Pulse Load",
    nameRu: "Загрузка",
    category: "buttons",
    world: "ink",
    tags: ["loading", "motion"],
    note: "Состояние процесса внутри той же кнопки.",
    css: `.spin { animation: spin 700ms linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }`,
  },
  {
    id: 21,
    slug: "alert-cut",
    name: "Alert Cut",
    nameRu: "Деструктив",
    category: "buttons",
    world: "paper",
    tags: ["danger", "quiet"],
    note: "Сдержанный красный только на действии удаления.",
    css: `.btn { color: #8a2a24; box-shadow: inset 0 0 0 1px #8a2a2444; }`,
  },
  {
    id: 22,
    slug: "confirm",
    name: "Confirm",
    nameRu: "Подтверждение",
    category: "buttons",
    world: "paper",
    tags: ["success", "quiet"],
    note: "Тихий зелёный. Не неон, не градиент.",
    css: `.btn { background: #1d3a28; color: #e8f3ec; }`,
  },
  {
    id: 23,
    slug: "orbit-fab",
    name: "Orbit FAB",
    nameRu: "FAB",
    category: "buttons",
    world: "night",
    tags: ["fab", "round"],
    note: "Плавающая круглая кнопка с мягкой тенью.",
    css: `.fab { width: 52px; height: 52px; border-radius: 50%; box-shadow: 0 8px 24px #0008; }`,
  },
  {
    id: 24,
    slug: "joined-pair",
    name: "Joined Pair",
    nameRu: "Сегмент",
    category: "buttons",
    world: "mist",
    tags: ["segment", "pair"],
    note: "Две кнопки делят одну рамку. Общий радиус снаружи.",
    css: `.pair { display: flex; border-radius: 10px; overflow: hidden; box-shadow: inset 0 0 0 1px #1a191633; }`,
  },
  {
    id: 25,
    slug: "paper-sheet",
    name: "Paper Sheet",
    nameRu: "Лист",
    category: "surfaces",
    world: "studio",
    tags: ["paper", "card"],
    note: "Тёплый лист с одной тенью. Базовая карточка.",
    css: `.card { background: #f6f1e8; border-radius: 16px; box-shadow: 0 1px 0 #0001, 0 12px 32px #0002; padding: 20px; }`,
  },
  {
    id: 26,
    slug: "inset-well",
    name: "Inset Well",
    nameRu: "Колодец",
    category: "surfaces",
    world: "ink",
    tags: ["inset", "well"],
    note: "Утопленная площадка для вложенного контента.",
    css: `.well { background: #0a0a09; box-shadow: inset 0 1px 2px #0008, 0 0 0 1px #ffffff0d; border-radius: 14px; }`,
  },
  {
    id: 27,
    slug: "hard-offset",
    name: "Hard Offset",
    nameRu: "Сдвиг тени",
    category: "surfaces",
    world: "paper",
    tags: ["brutal", "shadow"],
    note: "Жёсткая смещённая тень. Плакат, не продукт.",
    css: `.card { background: #fff; box-shadow: 8px 8px 0 #0c0c0b; border: 2px solid #0c0c0b; }`,
  },
  {
    id: 28,
    slug: "column-clip",
    name: "Column Clip",
    nameRu: "Вырезка",
    category: "surfaces",
    world: "paper",
    tags: ["editorial", "serif"],
    note: "Газетная колонка: линейки, серф, узкая мера.",
    css: `.clip { border-top: 2px solid #1a1916; border-bottom: 1px solid #1a1916; padding: 16px 0; }`,
  },
  {
    id: 29,
    slug: "ticket",
    name: "Ticket",
    nameRu: "Билет",
    category: "surfaces",
    world: "studio",
    tags: ["analog", "ticket"],
    note: "Перфорация по краю и отрывной корешок.",
    css: `.ticket { background: #f4efe4; mask: radial-gradient(6px at left, #0000 98%, #000) 0 / 100% 16px; }`,
  },
  {
    id: 30,
    slug: "polaroid",
    name: "Polaroid",
    nameRu: "Полароид",
    category: "surfaces",
    world: "mist",
    tags: ["analog", "frame"],
    note: "Белая рамка, поле подписи снизу.",
    css: `.polaroid { background: #fff; padding: 10px 10px 36px; box-shadow: 0 12px 28px #0002; }`,
  },
  {
    id: 31,
    slug: "tech-grid",
    name: "Tech Grid",
    nameRu: "Сетка",
    category: "surfaces",
    world: "grid",
    tags: ["technical", "grid"],
    note: "Модульная сетка как поверхность, не декор.",
    css: `.panel { background-image: linear-gradient(#ffffff0d 1px, transparent 1px), linear-gradient(90deg, #ffffff0d 1px, transparent 1px); background-size: 16px 16px; }`,
  },
  {
    id: 32,
    slug: "quote-rail",
    name: "Quote Rail",
    nameRu: "Цитата",
    category: "surfaces",
    world: "paper",
    tags: ["editorial", "quote"],
    note: "Левая рейка вместо кавычек.",
    css: `.quote { border-left: 3px solid #1a1916; padding-left: 16px; }`,
  },
  {
    id: 33,
    slug: "spec-table",
    name: "Spec Table",
    nameRu: "Спецификация",
    category: "surfaces",
    world: "ink",
    tags: ["technical", "table"],
    note: "Строки ключ/значение как чертёжная ведомость.",
    css: `.row { display: flex; justify-content: space-between; border-bottom: 1px dashed #ffffff18; padding: 8px 0; font-size: 12px; }`,
  },
  {
    id: 34,
    slug: "folder",
    name: "Folder",
    nameRu: "Папка",
    category: "surfaces",
    world: "studio",
    tags: ["analog", "file"],
    note: "Вкладка сверху, тело папки снизу.",
    css: `.tab { width: 72px; height: 14px; border-radius: 8px 8px 0 0; background: #e7dcc8; }`,
  },
  {
    id: 35,
    slug: "window",
    name: "Window",
    nameRu: "Окно",
    category: "surfaces",
    world: "ink",
    tags: ["chrome", "window"],
    note: "Заголовок окна, три точки, рабочее поле.",
    css: `.win { border-radius: 12px; overflow: hidden; box-shadow: 0 0 0 1px #ffffff14; }
.bar { height: 32px; background: #1c1c19; }`,
  },
  {
    id: 36,
    slug: "stack",
    name: "Stack",
    nameRu: "Стопка",
    category: "surfaces",
    world: "mist",
    tags: ["stack", "paper"],
    note: "Смещённые листы под верхним. Глубина стопки.",
    css: `.stack::before, .stack::after { content: ""; position: absolute; inset: 8px -6px auto; height: 100%; background: #ddd6c8; }`,
  },
  {
    id: 37,
    slug: "rule-box",
    name: "Rule Box",
    nameRu: "Линейки",
    category: "surfaces",
    world: "paper",
    tags: ["editorial", "rule"],
    note: "Только верхняя и нижняя линейки. Боков нет.",
    css: `.box { border-block: 1px solid #1a1916; padding: 16px 0; }`,
  },
  {
    id: 38,
    slug: "soft-lift",
    name: "Soft Lift",
    nameRu: "Подъём",
    category: "surfaces",
    world: "paper",
    tags: ["soft", "shadow"],
    note: "Большой размытый офсет. Карточка парит.",
    css: `.card { background: #fff; border-radius: 20px; box-shadow: 0 18px 40px #0c0c0b14; }`,
  },
  {
    id: 39,
    slug: "void-panel",
    name: "Void Panel",
    nameRu: "Пустота",
    category: "surfaces",
    world: "night",
    tags: ["quiet", "dark"],
    note: "Почти без границы. Панель читается тоном.",
    css: `.panel { background: #12131a; border-radius: 16px; }`,
  },
  {
    id: 40,
    slug: "notebook",
    name: "Notebook",
    nameRu: "Тетрадь",
    category: "surfaces",
    world: "paper",
    tags: ["analog", "lines"],
    note: "Линованная бумага и красное поле слева.",
    css: `.note { background: repeating-linear-gradient(#f6f1e8, #f6f1e8 27px, #d7cfc2 28px); border-left: 2px solid #b4554a55; }`,
  },
  {
    id: 41,
    slug: "postage",
    name: "Postage",
    nameRu: "Марка",
    category: "surfaces",
    world: "studio",
    tags: ["analog", "stamp"],
    note: "Зубцы марки через repeating-radial.",
    css: `.stamp { --c: #f2efe9; background: var(--c); filter: drop-shadow(0 8px 16px #0002); }`,
  },
  {
    id: 42,
    slug: "header-split",
    name: "Header Split",
    nameRu: "Шапка",
    category: "surfaces",
    world: "ink",
    tags: ["product", "header"],
    note: "Шапка отделена от тела. Карточка-документ.",
    css: `.head { padding: 12px 16px; border-bottom: 1px solid #ffffff14; }`,
  },
  {
    id: 43,
    slug: "stat-tile",
    name: "Stat Tile",
    nameRu: "Стат",
    category: "surfaces",
    world: "ink",
    tags: ["stat", "product"],
    note: "Крупная цифра, тихая подпись. Одна метрика.",
    css: `.num { font-size: 36px; font-variant-numeric: tabular-nums; letter-spacing: -0.04em; }`,
  },
  {
    id: 44,
    slug: "caption-frame",
    name: "Caption Frame",
    nameRu: "Подпись",
    category: "surfaces",
    world: "ink",
    tags: ["caption", "media"],
    note: "Изображение и плашка подписи одной ширины.",
    css: `.cap { font-size: 11px; letter-spacing: .08em; text-transform: uppercase; }`,
  },
  {
    id: 45,
    slug: "pin-board",
    name: "Pin Board",
    nameRu: "Доска",
    category: "surfaces",
    world: "studio",
    tags: ["analog", "pin"],
    note: "Канцелярская кнопка и лёгкий наклон листа.",
    css: `.pin { width: 10px; height: 10px; border-radius: 50%; background: #8a2a24; }`,
  },
  {
    id: 46,
    slug: "envelope",
    name: "Envelope",
    nameRu: "Конверт",
    category: "surfaces",
    world: "mist",
    tags: ["analog", "mail"],
    note: "Треугольный клапан и адресное поле.",
    css: `.flap { clip-path: polygon(0 0, 50% 55%, 100% 0); background: #ddd6c8; }`,
  },
  {
    id: 47,
    slug: "italic-display",
    name: "Italic Display",
    nameRu: "Курсив",
    category: "type",
    world: "paper",
    tags: ["serif", "editorial"],
    note: "Крупный курсив. Один заголовок — весь характер.",
    css: `h1 { font-family: "Instrument Serif", serif; font-style: italic; font-size: 42px; letter-spacing: -0.03em; }`,
  },
  {
    id: 48,
    slug: "tight-grotesk",
    name: "Tight Grotesk",
    nameRu: "Гротеск",
    category: "type",
    world: "ink",
    tags: ["sans", "tight"],
    note: "Отрицательный трекинг, сильный вес.",
    css: `h1 { font-weight: 600; letter-spacing: -0.06em; line-height: 0.95; }`,
  },
  {
    id: 49,
    slug: "chapter",
    name: "Chapter",
    nameRu: "Глава",
    category: "type",
    world: "paper",
    tags: ["editorial", "number"],
    note: "Номер главы мелкий, название крупное.",
    css: `.num { font-size: 11px; letter-spacing: .2em; }
h2 { font-family: "Instrument Serif", serif; font-size: 28px; }`,
  },
  {
    id: 50,
    slug: "overline",
    name: "Overline",
    nameRu: "Надзаголовок",
    category: "type",
    world: "ink",
    tags: ["kicker", "label"],
    note: "Маленькая метка над заголовком.",
    css: `.kicker { font-size: 10px; letter-spacing: .18em; text-transform: uppercase; opacity: .55; }`,
  },
  {
    id: 51,
    slug: "stacked",
    name: "Stacked",
    nameRu: "Стек",
    category: "type",
    world: "paper",
    tags: ["stack", "poster"],
    note: "Слова столбиком, разные кегли, один смысл.",
    css: `.stack { display: flex; flex-direction: column; line-height: 0.9; }`,
  },
  {
    id: 52,
    slug: "ghost-outline",
    name: "Ghost Outline",
    nameRu: "Контурный",
    category: "type",
    world: "night",
    tags: ["outline", "display"],
    note: "Обводка букв без заливки. Плакатный приём.",
    css: `h1 { -webkit-text-stroke: 1px #f2efe9; color: transparent; letter-spacing: 0.04em; }`,
  },
  {
    id: 53,
    slug: "mono-index",
    name: "Mono Index",
    nameRu: "Моно",
    category: "type",
    world: "grid",
    tags: ["mono", "technical"],
    note: "Технический индекс: путь, версия, метка.",
    css: `h1 { font-family: ui-monospace, monospace; font-size: 14px; font-weight: 400; }`,
  },
  {
    id: 54,
    slug: "drop-cap",
    name: "Drop Cap",
    nameRu: "Буквица",
    category: "type",
    world: "paper",
    tags: ["editorial", "drop"],
    note: "Первая буква на две строки. Книжный жест.",
    css: `p::first-letter { float: left; font-size: 3.2em; line-height: 0.8; padding-right: 8px; font-family: "Instrument Serif", serif; }`,
  },
  {
    id: 55,
    slug: "ruled-title",
    name: "Ruled Title",
    nameRu: "С линейками",
    category: "type",
    world: "paper",
    tags: ["rule", "editorial"],
    note: "Заголовок зажат между линейками на всю ширину.",
    css: `h1 { display: flex; align-items: center; gap: 12px; }
h1::before, h1::after { content: ""; flex: 1; height: 1px; background: currentColor; }`,
  },
  {
    id: 56,
    slug: "kicker-head",
    name: "Kicker + Head",
    nameRu: "Кикер",
    category: "type",
    world: "ink",
    tags: ["editorial", "kicker"],
    note: "Кикер / заголовок / лид. Классическая тройка.",
    css: `.kicker { font-size: 11px; }
h1 { font-size: 32px; }
.lead { opacity: .65; }`,
  },
  {
    id: 57,
    slug: "spine",
    name: "Spine",
    nameRu: "Корешок",
    category: "type",
    world: "studio",
    tags: ["rotated", "editorial"],
    note: "Вертикальная надпись как корешок книги.",
    css: `h1 { writing-mode: vertical-rl; transform: rotate(180deg); letter-spacing: .2em; }`,
  },
  {
    id: 58,
    slug: "small-caps",
    name: "Small Caps",
    nameRu: "Капитель",
    category: "type",
    world: "paper",
    tags: ["caps", "index"],
    note: "Капитель для рубрик и указателей.",
    css: `h1 { font-variant: small-caps; letter-spacing: .16em; font-weight: 500; }`,
  },
  {
    id: 59,
    slug: "pull-quote",
    name: "Pull Quote",
    nameRu: "Выноска",
    category: "type",
    world: "mist",
    tags: ["quote", "editorial"],
    note: "Крупная цитата с кавычкой-маркером.",
    css: `blockquote { font-family: "Instrument Serif", serif; font-size: 28px; font-style: italic; }`,
  },
  {
    id: 60,
    slug: "brackets",
    name: "Brackets",
    nameRu: "Скобки",
    category: "type",
    world: "grid",
    tags: ["technical", "frame"],
    note: "Заголовок в технических скобках.",
    css: `h1::before { content: "[ "; } h1::after { content: " ]"; }`,
  },
  {
    id: 61,
    slug: "strike-alt",
    name: "Strike Alt",
    nameRu: "Зачёркивание",
    category: "type",
    world: "paper",
    tags: ["edit", "alt"],
    note: "Старое зачёркнуто, новое рядом. Правка на глазах.",
    css: `s { text-decoration: line-through; opacity: .4; }`,
  },
  {
    id: 62,
    slug: "baseline",
    name: "Baseline",
    nameRu: "База",
    category: "type",
    world: "paper",
    tags: ["grid", "editorial"],
    note: "Заголовок сидит на явной базовой линии.",
    css: `h1 { border-bottom: 1px solid #1a1916; line-height: 1; padding-bottom: 6px; }`,
  },
  {
    id: 63,
    slug: "file-chip",
    name: "File Chip",
    nameRu: "Файл",
    category: "chips",
    world: "ink",
    tags: ["file", "chip"],
    note: "Имя файла, расширение, вес. Снимается крестом.",
    css: `.chip { display: flex; gap: 8px; align-items: center; border-radius: 8px; box-shadow: inset 0 0 0 1px #ffffff16; }`,
  },
  {
    id: 64,
    slug: "image-attach",
    name: "Image Attach",
    nameRu: "Изображение",
    category: "chips",
    world: "ink",
    tags: ["image", "attach"],
    note: "Превью 32×32 и имя. Вложение картинки.",
    css: `.thumb { width: 32px; height: 32px; border-radius: 4px; }`,
  },
  {
    id: 65,
    slug: "pdf-dossier",
    name: "PDF Dossier",
    nameRu: "PDF",
    category: "chips",
    world: "paper",
    tags: ["pdf", "doc"],
    note: "Иконка документа и мета. Канцелярский тон.",
    css: `.doc { display: flex; gap: 10px; padding: 10px 12px; background: #f6f1e8; }`,
  },
  {
    id: 66,
    slug: "audio-bar",
    name: "Audio Bar",
    nameRu: "Аудио",
    category: "chips",
    world: "night",
    tags: ["audio", "media"],
    note: "Волна и длительность. Звуковое вложение.",
    css: `.wave span { width: 2px; background: #f2efe9; animation: eq 1s ease-in-out infinite; }`,
  },
  {
    id: 67,
    slug: "link-card",
    name: "Link Card",
    nameRu: "Ссылка",
    category: "chips",
    world: "ink",
    tags: ["link", "unfurl"],
    note: "Мини-анфул: домен, заголовок, фавикон-точка.",
    css: `.unfurl { display: grid; gap: 2px; box-shadow: inset 0 0 0 1px #ffffff14; border-radius: 10px; }`,
  },
  {
    id: 68,
    slug: "tag-pill",
    name: "Tag Pill",
    nameRu: "Тег",
    category: "chips",
    world: "mist",
    tags: ["tag", "pill"],
    note: "Одиночный тег-капсула. Низкий контраст заливки.",
    css: `.tag { border-radius: 999px; padding: 4px 10px; font-size: 12px; background: #1a1916; color: #f2efe9; }`,
  },
  {
    id: 69,
    slug: "live-dot",
    name: "Live Dot",
    nameRu: "Статус",
    category: "chips",
    world: "ink",
    tags: ["status", "dot"],
    note: "Точка состояния и подпись. Живой индикатор.",
    css: `.dot { width: 8px; height: 8px; border-radius: 50%; background: #7d9b7a; }`,
  },
  {
    id: 70,
    slug: "count-mark",
    name: "Count Mark",
    nameRu: "Счётчик",
    category: "chips",
    world: "paper",
    tags: ["badge", "count"],
    note: "Числовой бейдж. Табличные цифры.",
    css: `.badge { min-width: 20px; height: 20px; border-radius: 999px; font-variant-numeric: tabular-nums; }`,
  },
  {
    id: 71,
    slug: "removable",
    name: "Removable",
    nameRu: "Сброс",
    category: "chips",
    world: "ink",
    tags: ["chip", "remove"],
    note: "Чип фильтра с явным снятием.",
    css: `.chip button { width: 20px; height: 20px; border-radius: 50%; }`,
  },
  {
    id: 72,
    slug: "face-stack",
    name: "Face Stack",
    nameRu: "Аватары",
    category: "chips",
    world: "paper",
    tags: ["avatar", "stack"],
    note: "Стопка лиц с перекрытием и счётчиком.",
    css: `.faces > * { margin-left: -8px; box-shadow: 0 0 0 2px #efeae1; }`,
  },
  {
    id: 73,
    slug: "upload-bar",
    name: "Upload Bar",
    nameRu: "Прогресс",
    category: "chips",
    world: "ink",
    tags: ["progress", "file"],
    note: "Файл в процессе загрузки. Полоса внутри чипа.",
    css: `.bar { height: 2px; background: #f2efe9; width: 62%; }`,
  },
  {
    id: 74,
    slug: "bundle",
    name: "Bundle",
    nameRu: "Пачка",
    category: "chips",
    world: "mist",
    tags: ["folder", "count"],
    note: "Папка и число файлов внутри.",
    css: `.bundle { display: flex; gap: 8px; align-items: center; }`,
  },
  {
    id: 75,
    slug: "mention",
    name: "Mention",
    nameRu: "Упоминание",
    category: "chips",
    world: "ink",
    tags: ["mention", "user"],
    note: "Аватар-инициал и @имя.",
    css: `.at { font-weight: 500; }`,
  },
  {
    id: 76,
    slug: "hash",
    name: "Hash",
    nameRu: "Хэш",
    category: "chips",
    world: "paper",
    tags: ["tag", "hash"],
    note: "Хэштег без заливки, только литера.",
    css: `.hash { color: #6e6b64; } .hash b { color: #1a1916; }`,
  },
  {
    id: 77,
    slug: "build-stamp",
    name: "Build Stamp",
    nameRu: "Версия",
    category: "chips",
    world: "grid",
    tags: ["version", "mono"],
    note: "Штамп сборки моноширинным.",
    css: `.ver { font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: .04em; }`,
  },
  {
    id: 78,
    slug: "priority",
    name: "Priority",
    nameRu: "Приоритет",
    category: "chips",
    world: "paper",
    tags: ["flag", "priority"],
    note: "Флажок приоритета. Цвет только на маркере.",
    css: `.flag { width: 8px; height: 12px; background: #8a2a24; clip-path: polygon(0 0, 100% 0, 100% 70%, 50% 100%, 0 70%); }`,
  },
  {
    id: 79,
    slug: "date-chip",
    name: "Date Chip",
    nameRu: "Дата",
    category: "chips",
    world: "ink",
    tags: ["date", "meta"],
    note: "Календарная мета. День и месяц раздельно.",
    css: `.date { display: grid; text-align: center; }
.day { font-size: 16px; font-variant-numeric: tabular-nums; }`,
  },
  {
    id: 80,
    slug: "weight-meta",
    name: "Weight Meta",
    nameRu: "Размер",
    category: "chips",
    world: "ink",
    tags: ["meta", "size"],
    note: "Вес файла как тихая мета рядом с именем.",
    css: `.meta { font-size: 11px; opacity: .5; font-variant-numeric: tabular-nums; }`,
  },
  {
    id: 81,
    slug: "hairline-field",
    name: "Hairline Field",
    nameRu: "Поле",
    category: "controls",
    world: "ink",
    tags: ["input", "quiet"],
    note: "Волосная рамка, высота 44. Фокус — кольцо.",
    css: `input { height: 44px; box-shadow: inset 0 0 0 1px #ffffff18; background: #121211; border-radius: 10px; }`,
  },
  {
    id: 82,
    slug: "underscore-input",
    name: "Underscore Input",
    nameRu: "Линия",
    category: "controls",
    world: "paper",
    tags: ["input", "editorial"],
    note: "Только нижняя линия. Редакционный ввод.",
    css: `input { border: 0; border-bottom: 1px solid #1a1916; background: transparent; border-radius: 0; }`,
  },
  {
    id: 83,
    slug: "search-well",
    name: "Search Well",
    nameRu: "Поиск",
    category: "controls",
    world: "mist",
    tags: ["search", "input"],
    note: "Иконка внутри колодца. Поле-поиск.",
    css: `.search { display: flex; align-items: center; gap: 8px; border-radius: 999px; background: #efeae1; }`,
  },
  {
    id: 84,
    slug: "switch",
    name: "Switch",
    nameRu: "Переключатель",
    category: "controls",
    world: "ink",
    tags: ["toggle", "switch"],
    note: "Короткий ход бегунка. Состояние цветом дорожки.",
    css: `.track { width: 44px; height: 26px; border-radius: 999px; }
.knob { width: 20px; height: 20px; border-radius: 50%; }`,
  },
  {
    id: 85,
    slug: "segmented",
    name: "Segmented",
    nameRu: "Сегменты",
    category: "controls",
    world: "paper",
    tags: ["segment", "tabs"],
    note: "Скользящая пилюля под сегментами.",
    css: `.seg { display: grid; grid-auto-flow: column; background: #e7e1d6; border-radius: 10px; padding: 3px; }`,
  },
  {
    id: 86,
    slug: "check-row",
    name: "Check Row",
    nameRu: "Чекбокс",
    category: "controls",
    world: "ink",
    tags: ["checkbox", "row"],
    note: "Строка с чекбоксом и подписью. Вся строка — хит.",
    css: `.box { width: 18px; height: 18px; border-radius: 4px; box-shadow: inset 0 0 0 1px #ffffff28; }`,
  },
  {
    id: 87,
    slug: "radio-card",
    name: "Radio Card",
    nameRu: "Радио",
    category: "controls",
    world: "paper",
    tags: ["radio", "card"],
    note: "Выбор карточкой, не точкой. Состояние рамкой.",
    css: `.opt[data-on="true"] { box-shadow: inset 0 0 0 2px #0c0c0b; }`,
  },
  {
    id: 88,
    slug: "range",
    name: "Range",
    nameRu: "Слайдер",
    category: "controls",
    world: "ink",
    tags: ["slider", "range"],
    note: "Тонкая дорожка, круглый бегунок.",
    css: `input[type=range] { appearance: none; height: 2px; background: #ffffff22; }`,
  },
  {
    id: 89,
    slug: "spec-area",
    name: "Spec Area",
    nameRu: "Текстовое",
    category: "controls",
    world: "paper",
    tags: ["textarea", "input"],
    note: "Многострочное поле с счётчиком знаков.",
    css: `textarea { min-height: 72px; resize: none; box-shadow: inset 0 0 0 1px #1a191622; }`,
  },
  {
    id: 90,
    slug: "select",
    name: "Select",
    nameRu: "Селект",
    category: "controls",
    world: "ink",
    tags: ["select", "menu"],
    note: "Закрытый селект с шевроном. Не нативный вид.",
    css: `.sel { display: flex; justify-content: space-between; height: 44px; border-radius: 10px; }`,
  },
  {
    id: 91,
    slug: "otp",
    name: "OTP",
    nameRu: "Код",
    category: "controls",
    world: "paper",
    tags: ["otp", "code"],
    note: "Четыре клетки кода. Фокус на активной.",
    css: `.cell { width: 40px; height: 48px; text-align: center; box-shadow: inset 0 0 0 1px #1a191633; }`,
  },
  {
    id: 92,
    slug: "stepper",
    name: "Stepper",
    nameRu: "Степпер",
    category: "controls",
    world: "mist",
    tags: ["stepper", "number"],
    note: "Минус / значение / плюс. Табличное число.",
    css: `.step { display: grid; grid-template-columns: 36px 1fr 36px; height: 40px; }`,
  },
  {
    id: 93,
    slug: "info-rail",
    name: "Info Rail",
    nameRu: "Инфо",
    category: "chrome",
    world: "ink",
    tags: ["banner", "info"],
    note: "Информационная рейка с иконкой слева.",
    css: `.banner { display: flex; gap: 10px; box-shadow: inset 3px 0 0 #c8c4bb; }`,
  },
  {
    id: 94,
    slug: "warn-strip",
    name: "Warn Strip",
    nameRu: "Предупреждение",
    category: "chrome",
    world: "paper",
    tags: ["banner", "warn"],
    note: "Узкая полоса предупреждения. Янтарь только на маркере.",
    css: `.warn { background: #f3ead4; box-shadow: inset 3px 0 0 #8a6a24; }`,
  },
  {
    id: 95,
    slug: "toast",
    name: "Toast",
    nameRu: "Тост",
    category: "chrome",
    world: "night",
    tags: ["toast", "success"],
    note: "Плавающее подтверждение. Коротко и снято.",
    css: `.toast { background: #17180f; border-radius: 12px; box-shadow: 0 16px 40px #0008; }`,
  },
  {
    id: 96,
    slug: "inline-note",
    name: "Inline Note",
    nameRu: "Заметка",
    category: "chrome",
    world: "paper",
    tags: ["note", "inline"],
    note: "Заметка в потоке текста. Не модалка.",
    css: `.note { font-size: 13px; background: #efe6d2; border-radius: 4px; padding: 10px 12px; }`,
  },
  {
    id: 97,
    slug: "empty",
    name: "Empty",
    nameRu: "Пусто",
    category: "chrome",
    world: "ink",
    tags: ["empty", "state"],
    note: "Пустое состояние: жест, заголовок, одно действие.",
    css: `.empty { text-align: center; opacity: .85; }`,
  },
  {
    id: 98,
    slug: "tabs",
    name: "Tabs",
    nameRu: "Табы",
    category: "chrome",
    world: "paper",
    tags: ["tabs", "nav"],
    note: "Нижняя линейка у активного. Без пилюли.",
    css: `.tab[data-on="true"] { box-shadow: inset 0 -2px 0 #0c0c0b; }`,
  },
  {
    id: 99,
    slug: "crumbs",
    name: "Crumbs",
    nameRu: "Крошки",
    category: "chrome",
    world: "ink",
    tags: ["nav", "breadcrumb"],
    note: "Путь с тихим разделителем. Последний — текущий.",
    css: `.crumb { display: flex; gap: 8px; font-size: 13px; }`,
  },
  {
    id: 100,
    slug: "pages",
    name: "Pages",
    nameRu: "Пагинация",
    category: "chrome",
    world: "paper",
    tags: ["pagination", "nav"],
    note: "Номера страниц. Активная — инверсия.",
    css: `.pg[data-on="true"] { background: #0c0c0b; color: #f2efe9; }`,
  },
];

export const SPECIMEN_BY_ID = new Map(SPECIMENS.map((s) => [s.id, s]));
export const SPECIMEN_BY_SLUG = new Map(SPECIMENS.map((s) => [s.slug, s]));

export function padId(id: number) {
  return String(id).padStart(3, "0");
}

export function categoryBySlug(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function specimensInCategory(slug: CategorySlug) {
  return SPECIMENS.filter((s) => s.category === slug);
}

export function searchSpecimens(query: string, list: Specimen[] = SPECIMENS) {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter((s) => {
    const hay = `${s.id} ${padId(s.id)} ${s.name} ${s.nameRu} ${s.slug} ${s.tags.join(" ")} ${s.note}`.toLowerCase();
    return hay.includes(q);
  });
}
